"""
app.py — Flask web UI for the Screenshot Tool (no emulator / no Appium).

Flows:
  • Sign in (required) so every batch is tagged with who generated it.
  • Upload an Excel (serviceDetails.xlsx pattern) -> preview rows -> "Generate
    Screenshots" -> renders each row to screenshots/<City>/<ServiceName>.png,
    zips the folder, offers a download.
  • Manual entry -> renders a single Service Information screen, shows it, and
    saves it under a city folder you can download.
"""
from __future__ import annotations

import csv
import io
import json
import os
import secrets
import shutil
import uuid
import zipfile
from datetime import datetime, timedelta, timezone

from flask import (Flask, Response, abort, jsonify, redirect, render_template, request,
                   send_file, session, url_for)
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.utils import secure_filename
from dotenv import load_dotenv

from auth import current_user, load_users, verify_password
from data import (DEFAULT_BOOKING, DEFAULT_BOOKING_TIME, REQUIRED_COLUMNS,
                  clean_file_name, default_booking_date, format_booking,
                  includes_for, load_includes, read_excel, row_to_record,
                  safe_folder, staggered_booking_times, today_str)
from renderer import ServiceRecord, render_service_screen

_HERE = os.path.dirname(os.path.abspath(__file__))
load_dotenv(os.path.join(_HERE, "..", ".env"))
load_dotenv(os.path.join(_HERE, ".env"))
RUNS_DIR = os.path.join(_HERE, "runs")
os.makedirs(RUNS_DIR, exist_ok=True)
os.environ.setdefault("RUNS_DIR", RUNS_DIR)


def _secret_key() -> str:
    env = os.environ.get("SECRET_KEY", "").strip()
    if env:
        return env
    path = os.path.join(RUNS_DIR, ".secret_key")
    if os.path.isfile(path):
        with open(path, encoding="utf-8") as f:
            return f.read().strip()
    key = secrets.token_hex(32)
    with open(path, "w", encoding="utf-8") as f:
        f.write(key)
    return key


app = Flask(__name__)
app.secret_key = _secret_key()
app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1)
app.config["MAX_CONTENT_LENGTH"] = 25 * 1024 * 1024  # 25 MB uploads
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"
app.permanent_session_lifetime = timedelta(days=14)

_OPEN_ENDPOINTS = {"login", "login_post", "static"}


@app.before_request
def _require_login():
    if request.endpoint in _OPEN_ENDPOINTS or request.endpoint is None:
        return None
    if not session.get("user"):
        return redirect(url_for("login", next=request.path))
    return None


@app.context_processor
def _inject_user():
    return {"current_user": current_user()}


def _run_dir(run_id: str) -> str:
    d = os.path.join(RUNS_DIR, secure_filename(run_id))
    if not os.path.isdir(d):
        abort(404)
    return d


def _client_ip() -> str:
    fwd = (request.headers.get("X-Forwarded-For") or "").split(",")[0].strip()
    return fwd or (request.remote_addr or "")


def _append_audit(payload: dict) -> None:
    path = os.path.join(RUNS_DIR, "audit.jsonl")
    with open(path, "a", encoding="utf-8") as f:
        f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def _write_meta(rd: str, run_id: str, **fields) -> None:
    payload = {
        "run_id": run_id,
        "user": current_user() or "unknown",
        "created_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
        "ip": _client_ip(),
        **fields,
    }
    with open(os.path.join(rd, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
    with open(os.path.join(rd, "GENERATED_BY.txt"), "w", encoding="utf-8") as f:
        f.write(f"Generated by: {payload['user']}\n")
        f.write(f"Generated at: {payload['created_at']}\n")
        if payload.get("kind"):
            f.write(f"Type: {payload['kind']}\n")
        if payload.get("count") is not None:
            f.write(f"Screenshots: {payload['count']}\n")
        if payload.get("ip"):
            f.write(f"IP: {payload['ip']}\n")
    _append_audit(payload)


def _read_meta(rd: str) -> dict:
    path = os.path.join(rd, "meta.json")
    if not os.path.isfile(path):
        return {}
    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except (OSError, json.JSONDecodeError):
        return {}


def _zip_folder(src_folder: str, zip_path: str, extra_files: list[tuple[str, str]] | None = None) -> None:
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, _dirs, files in os.walk(src_folder):
            for name in files:
                fp = os.path.join(root, name)
                arc = os.path.relpath(fp, os.path.dirname(src_folder))
                zf.write(fp, arc)
        for arc, fp in extra_files or []:
            if os.path.isfile(fp):
                zf.write(fp, arc)


# ── Auth ─────────────────────────────────────────────────────────────────────
@app.get("/login")
def login():
    if session.get("user"):
        return redirect(url_for("index"))
    nxt = request.args.get("next") or url_for("index")
    return render_template("login.html", next=nxt, error=None)


@app.post("/login")
def login_post():
    username = request.form.get("username", "")
    password = request.form.get("password", "")
    nxt = request.form.get("next") or url_for("index")
    if not nxt.startswith("/"):
        nxt = url_for("index")
    user = verify_password(username, password)
    if not user:
        if not load_users():
            err = "No users configured. Put AUTH_USERS in .env or run: python set_user.py <username>"
        else:
            err = "Invalid username or password."
        return render_template("login.html", next=nxt, error=err), 401
    session["user"] = user
    session.permanent = True
    return redirect(nxt)


@app.get("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# ── Home ─────────────────────────────────────────────────────────────────────
@app.get("/")
def index():
    return render_template("index.html", required=REQUIRED_COLUMNS,
                           default_booking=DEFAULT_BOOKING,
                           min_date=today_str(), default_date=default_booking_date(),
                           default_time=DEFAULT_BOOKING_TIME)


def _read_generated_by_txt(rd: str) -> dict:
    path = os.path.join(rd, "GENERATED_BY.txt")
    if not os.path.isfile(path):
        return {}
    out = {}
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                if ":" not in line:
                    continue
                k, v = line.split(":", 1)
                k, v = k.strip().lower(), v.strip()
                if k == "generated by":
                    out["user"] = v
                elif k == "generated at":
                    out["created_at"] = v
                elif k == "type":
                    out["kind"] = v
                elif k == "screenshots":
                    out["count"] = v
                elif k == "ip":
                    out["ip"] = v
    except OSError:
        return {}
    return out


def _folder_time(rd: str) -> str:
    try:
        ts = os.path.getmtime(rd)
    except OSError:
        return ""
    return datetime.fromtimestamp(ts, timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _png_count(rd: str) -> int:
    shots = os.path.join(rd, "screenshots")
    n = 0
    if not os.path.isdir(shots):
        return 0
    for root, _dirs, files in os.walk(shots):
        n += sum(1 for f in files if f.lower().endswith(".png"))
    return n


def _list_runs(user_filter: str = "") -> list[dict]:
    runs = []
    if not os.path.isdir(RUNS_DIR):
        return runs
    for name in os.listdir(RUNS_DIR):
        rd = os.path.join(RUNS_DIR, name)
        if not os.path.isdir(rd):
            continue
        has_zip = os.path.isfile(os.path.join(rd, "screenshots.zip"))
        has_shots = os.path.isdir(os.path.join(rd, "screenshots"))
        try:
            listing = os.listdir(rd)
        except OSError:
            continue
        has_xlsx = any(f.lower().endswith((".xlsx", ".xls")) for f in listing)
        meta = _read_meta(rd) or _read_generated_by_txt(rd)
        if not meta and not has_zip and not has_shots and not has_xlsx:
            continue
        user = str(meta.get("user") or "unknown")
        if user_filter and user.lower() != user_filter.lower():
            continue
        xlsx = next((f for f in listing if f.lower().endswith((".xlsx", ".xls"))), "")
        runs.append({
            "run_id": name,
            "user": user,
            "created_at": meta.get("created_at") or _folder_time(rd),
            "kind": meta.get("kind") or ("excel" if xlsx else "manual" if has_shots else ""),
            "count": meta.get("count") if meta.get("count") not in (None, "") else _png_count(rd),
            "detail": meta.get("detail") or xlsx or "",
            "ip": meta.get("ip", ""),
            "has_zip": has_zip,
        })
    runs.sort(key=lambda r: r["created_at"], reverse=True)
    return runs


# ── History ───────────────────────────────────────────────────────────────────
@app.get("/history")
def history():
    user_filter = request.args.get("user", "").strip()
    runs = _list_runs(user_filter)
    users = sorted({r["user"] for r in _list_runs()})
    return render_template("history.html", runs=runs, users=users,
                           user_filter=user_filter)


@app.get("/api/history")
def api_history():
    user_filter = request.args.get("user", "").strip()
    return jsonify({"runs": _list_runs(user_filter)})


@app.get("/history.csv")
def history_csv():
    user_filter = request.args.get("user", "").strip()
    rows = _list_runs(user_filter)
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=["created_at", "user", "kind", "count", "detail", "ip", "run_id"])
    w.writeheader()
    for r in rows:
        w.writerow({k: r.get(k, "") for k in w.fieldnames})
    return Response(
        buf.getvalue(),
        mimetype="text/csv",
        headers={"Content-Disposition": "attachment; filename=screenshot-history.csv"},
    )


# ── Excel upload -> preview ───────────────────────────────────────────────────
@app.post("/upload")
def upload():
    file = request.files.get("excel")
    if not file or file.filename == "":
        return render_template("index.html", required=REQUIRED_COLUMNS,
                               default_booking=DEFAULT_BOOKING,
                               error="Please choose an .xlsx file to upload."), 400

    run_id = uuid.uuid4().hex[:12]
    rd = os.path.join(RUNS_DIR, run_id)
    os.makedirs(rd, exist_ok=True)
    xlsx_path = os.path.join(rd, secure_filename(file.filename))
    file.save(xlsx_path)

    try:
        df, missing = read_excel(xlsx_path)
    except Exception as e:  # noqa: BLE001
        shutil.rmtree(rd, ignore_errors=True)
        return render_template("index.html", required=REQUIRED_COLUMNS,
                               default_booking=DEFAULT_BOOKING,
                               error=f"Could not read the Excel file: {e}"), 400

    if missing:
        shutil.rmtree(rd, ignore_errors=True)
        return render_template("index.html", required=REQUIRED_COLUMNS,
                               default_booking=DEFAULT_BOOKING,
                               error=f"Missing required columns: {', '.join(missing)}"), 400

    _write_meta(
        rd, run_id,
        kind="excel-upload",
        count=len(df),
        detail=os.path.basename(xlsx_path),
        filename=os.path.basename(xlsx_path),
    )
    preview = df.head(50).fillna("").to_dict(orient="records")
    cities = sorted({str(r.get("City", "")).strip() for r in df.fillna("").to_dict("records") if str(r.get("City", "")).strip()})
    has_booking_col = "BookingDateTime" in df.columns
    return render_template("preview.html", run_id=run_id,
                           columns=list(df.columns), rows=preview,
                           total=len(df), cities=cities,
                           filename=os.path.basename(xlsx_path),
                           has_booking_col=has_booking_col,
                           min_date=today_str(), default_date=default_booking_date())


# ── Generate all screenshots -> zip ───────────────────────────────────────────
@app.post("/generate/<run_id>")
def generate(run_id):
    rd = _run_dir(run_id)
    xlsx = next((os.path.join(rd, f) for f in os.listdir(rd) if f.lower().endswith((".xlsx", ".xls"))), None)
    if not xlsx:
        abort(404)

    df, missing = read_excel(xlsx)
    if missing:
        abort(400)

    includes_map = load_includes()
    # Date from the preview page; time is a random 30-minute slot between 9 AM
    # and 3 PM for each row that does not already have BookingDateTime.
    bd = request.form.get("booking_date", "").strip() or default_booking_date()
    bookings = iter(staggered_booking_times(bd, len(df)))

    shots_dir = os.path.join(rd, "screenshots")
    shutil.rmtree(shots_dir, ignore_errors=True)
    os.makedirs(shots_dir, exist_ok=True)

    results = []
    for _, row in df.iterrows():
        rec = row_to_record(row, includes_map, default_booking=next(bookings))
        if not rec.service_name or not rec.city:
            continue
        city_dir = os.path.join(shots_dir, safe_folder(rec.city))
        os.makedirs(city_dir, exist_ok=True)
        fname = clean_file_name(rec.service_name) + ".png"
        out = os.path.join(city_dir, fname)
        render_service_screen(rec, out)
        results.append({
            "city": safe_folder(rec.city),
            "file": fname,
            "rel": os.path.relpath(out, shots_dir).replace(os.sep, "/"),
        })

    user = current_user() or "unknown"
    _write_meta(
        rd,
        run_id,
        kind="excel",
        count=len(results),
        detail=os.path.basename(xlsx),
        filename=os.path.basename(xlsx),
    )
    zip_path = os.path.join(rd, "screenshots.zip")
    _zip_folder(shots_dir, zip_path, extra_files=[("GENERATED_BY.txt", os.path.join(rd, "GENERATED_BY.txt"))])

    by_city: dict[str, list] = {}
    for r in results:
        by_city.setdefault(r["city"], []).append(r)

    return render_template("results.html", run_id=run_id, by_city=by_city,
                           count=len(results), cities=len(by_city),
                           generated_by=user)


# ── Manual single render ──────────────────────────────────────────────────────
@app.post("/manual")
def manual():
    f = request.form
    service_name = f.get("service_name", "").strip()
    city = f.get("city", "").strip()
    if not service_name or not city:
        return render_template("index.html", required=REQUIRED_COLUMNS,
                               default_booking=DEFAULT_BOOKING,
                               error="Service Name and City are required."), 400

    run_id = uuid.uuid4().hex[:12]
    rd = os.path.join(RUNS_DIR, run_id)
    shots_dir = os.path.join(rd, "screenshots")
    os.makedirs(shots_dir, exist_ok=True)

    booking = format_booking(
        f.get("booking_date", "").strip(),
        f.get("booking_time", DEFAULT_BOOKING_TIME).strip(),
    )
    rec = ServiceRecord(
        amount=f.get("amount", "").strip(),
        service_name=service_name,
        estimated_time=f.get("estimated_time", "").strip(),
        city=city,
        zipcode=f.get("zipcode", "").strip().zfill(5) if f.get("zipcode", "").strip().isdigit() else f.get("zipcode", "").strip(),
        customer_name=f.get("customer_name", "").strip(),
        customer_instructions=f.get("customer_instructions", "").strip(),
        booking_datetime=booking,
        includes=includes_for(service_name),
    )
    city_dir = os.path.join(shots_dir, safe_folder(city))
    os.makedirs(city_dir, exist_ok=True)
    fname = clean_file_name(service_name) + ".png"
    out = os.path.join(city_dir, fname)
    render_service_screen(rec, out)

    user = current_user() or "unknown"
    _write_meta(
        rd,
        run_id,
        kind="manual",
        count=1,
        detail=f"{fname} ({safe_folder(city)})",
    )
    _zip_folder(shots_dir, os.path.join(rd, "screenshots.zip"),
                extra_files=[("GENERATED_BY.txt", os.path.join(rd, "GENERATED_BY.txt"))])

    rel = os.path.relpath(out, shots_dir).replace(os.sep, "/")
    return render_template("manual_result.html", run_id=run_id,
                           city=safe_folder(city), file=fname, rel=rel,
                           generated_by=user)


# ── Serve generated images + zip ──────────────────────────────────────────────
@app.get("/img/<run_id>/<path:relpath>")
def img(run_id, relpath):
    rd = _run_dir(run_id)
    fp = os.path.normpath(os.path.join(rd, "screenshots", relpath))
    if not fp.startswith(os.path.join(rd, "screenshots")) or not os.path.isfile(fp):
        abort(404)
    return send_file(fp, mimetype="image/png")


@app.get("/download/<run_id>")
def download(run_id):
    rd = _run_dir(run_id)
    zip_path = os.path.join(rd, "screenshots.zip")
    if not os.path.isfile(zip_path):
        abort(404)
    meta = _read_meta(rd)
    user = secure_filename(meta.get("user") or "screenshots") or "screenshots"
    return send_file(zip_path, as_attachment=True, download_name=f"screenshots-{user}.zip")


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000, debug=True)
